workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v14
      - node-v16
      - node-v18

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    working_directory: ~/working_directory
    steps:
      - run:
          name: Versions
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v1-{{ .Branch }}-
            - npm-v1-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules

  node-v14:
    <<: *node-base
    docker:
      - image: node:20
  node-v16:
    <<: *node-base
    docker:
      - image: node:20
  node-v18:
    <<: *node-base
    docker:
      - image: node:20